### ISSUE TITLE
Make tests run on Travis

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-map-matching.js#9]
Looks like [it's breaking](https://travis-ci.org/mapbox/mapbox-map-matching.js) because Zuul wants to be executed in the browser?

**Comment by freenerd** [comment]
@planemad do you want to have a look at this again? tests also don't work for me locally with:

```bash
$npm test

> mapbox-match.js@0.0.1 test mapbox-match.js
> zuul --local -- test/test.js

open the following url in a browser:
http://localhost:51252/__zuul
module.js:338
    throw err;
          ^
Error: Cannot find module 'st'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (mapbox-match.js/test/server.js:1:72)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by planemad** [comment]
@freenerd don't think I can look into this till next week. Just got back from vacation and have my hands full with priority work. Can this wait?
